
PHP_VERSION=${PHP_VERSION:-7.2}
PHP_ETC=${PHP_ETC:-/etc/php/$PHP_VERSION}
DEBIAN_FRONTEND=${DEBIAN_FRONTEND:-noninteractive}

MARIADB_HOST=${DATABASE_HOST:-localhost}
MARIADB_ROOT_USERNAME=${MARIADB_ROOT_USERNAME:-root}
MARIADB_ROOT_PASSWORD=${MARIADB_ROOT_PASSWORD:-open}
MARIADB_NORMAL_USERNAME=${MARIADB_NORMAL_USERNAME:-service}
MARIADB_NORMAL_PASSWORD=${MARIADB_NORMAL_PASSWORD:-open}