
# Installers
ZPARSER_INSTALLER="${ZPARSER_INSTALLER:=$ZPARSER_DEFAULT}"
ZCOMPILER_INSTALLER="${ZCOMPILER_INSTALLER:=$ZCOMPILER_DEFAULT}"
PHALCON_INSTALLER="${PHALCON_INSTALLER:=$PHALCON_DEFAULT}"
NODEJS_INSTALLER="${NODEJS_INSTALL:=$NODEJS_DEFAULT}"
