
VERSION=0.1.0
ZPARSER_DEFAULT_VERSION=1.2.0
ZCOMPILER_DEFAULT_VERSION=0.11.9
PHALCON_DEFAULT_VERSION=3.4.2

# Install defaults
PHALCON_DEFAULT=repository:stable
ZPARSER_DEFAULT=tarball:$ZPARSER_DEFAULT_VERSION
ZCOMPILER_DEFAULT=phar:$ZCOMPILER_DEFAULT_VERSION
NODEJS_DEFAULT=repository:10

# Install
ZPARSER_INSTALL="${ZPARSER_INSTALL:=$ZPARSER_DEFAULT}"
ZCOMPILER_INSTALL="${ZCOMPILER_INSTALL:=$ZCOMPILER_DEFAULT}"
PHALCON_INSTALL="${PHALCON_INSTALL:=$PHALCON_DEFAULT}"
NODEJS_INSTALL=

# PHP SAPI list, default is cli only.
PHP_SAPI_LIST="${PHP_SAPI_LIST:=cli}"

SOFTWARE_INSTALL_ROOT=${SOFTWARE_INSTALL_ROOT:=~/opt}

# Colorize provisioning.
COLOR_SECTION='\e[94m'
COLOR_NOTICE='\e[32m'
COLOR_ERROR='\e[91m'
