#!/usr/bin/env bash
SETUP_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" > /dev/null 2>&1 && pwd )"
LIB_DIR="$SETUP_DIR/lib"
CUSTOM_DIR="$SETUP_DIR/custom"

source "$LIB_DIR/common.sh"
source "$LIB_DIR/menu.sh"

menuInit
initCommon "$(menuPlatformName "$1")"
menuStart
